### ISSUE TITLE
Question: v0.0.9 kube-vip-cloud-controller.yaml Image Verification

### ISSUE THREAD

**Issue by jarpat** [kube-vip/kube-vip-cloud-provider#101]
Hey,

I'm downloading the `kube-vip-cloud-controller.yaml` manifest here https://github.com/kube-vip/kube-vip-cloud-provider/blob/v0.0.9/manifest/kube-vip-cloud-controller.yaml from the `v0.0.9` tag 

I noticed that the image on L64 is pointing to `ghcr.io/kube-vip/kube-vip-cloud-provider:v0.0.8` should it be `v0.0.9`?

Thanks,
Jay

**Comment by lubronzhan** [comment]
Yeah it's not tagged on the newest release. 
But you can just use the main branch's manifest, it's pointing to v0.0.9

**Comment by lubronzhan** [comment]
Ok this time I updated the manifest first before cutting a release.
