### ISSUE TITLE
ConfigMap IP Range Bug!

### ISSUE THREAD

**Issue by hugo345816** [kube-vip/kube-vip-cloud-provider#11]
kubectl create configmap --namespace kube-system kubevip --from-literal range-global=192.168.0.200-192.168.0.202

if `range` ip pool is over ip/prefix 24，kube-vip-cloud-provider will be crash.

example:
cidr-global: 192.168.0.0/20       ----  OK
range-global: 192.168.0.1-192.168.0.255    ----- OK
range-global: 192.168.0.1-192.168.1.255    ------- kube-vip-cloud-provider will crash with no logs.
range-global: 192.168.0.1-192.168.0.255,192.168.1.0-192.168.1.255   ------- OK too

**Comment by thebsdbox** [comment]
Good catch, i'll look into that.
