### ISSUE TITLE
Pod kube-vip-cloud-provider-0 fails on K3S

### ISSUE THREAD

**Issue by emulated24** [kube-vip/kube-vip-cloud-provider#20]
Hi,
I am running latest K3S three-node cluster on DietPI ARM64 OS, all nodes are RPI4b with 8GB RAM. All nodes are masters in HA with embedded storage.
Kube-vip was deployed with arp, controlplane and services options. It runs fine, I can reach the cluster via the VIP from my laptop.

I have installed kube-vip-cloud-provider as instructed, but the pod fails:

```
NAMESPACE     NAME                                     READY   STATUS             RESTARTS        AGE
kube-system   kube-vip-cloud-provider-0                0/1     CrashLoopBackOff   7 (3m28s ago)   14m
```

Content of the log:
`standard_init_linux.go:228: exec user process caused: exec format error`

It looks like the compatibility issue with the ARM64 platform, which is puzzling as kube-vip runs absolutely fine.

**Comment by emulated24** [comment]
Nope, still not solved.

**Comment by thebsdbox** [comment]
Can you see which image it is running?

**Comment by emulated24** [comment]
How can I check?

**Comment by thebsdbox** [comment]
The container runtime should automatically pull for your architecture...

`kubectl describe pods -n kube-system   kube-vip-cloud-provider-0  | grep Image` You can reapply the yaml to move to the newer image.

**Comment by emulated24** [comment]
Apologies, this was solved long time ago.
