### ISSUE TITLE
Does tag 0.0.1 support arm64?

### ISSUE THREAD

**Issue by braucktoon** [kube-vip/kube-vip-cloud-provider#24]
Hi. I am getting exec format error when spinning up image kubevip/kube-vip-cloud-provider:0.0.1.  According to docker hub that tag does support arm64.  I am running k3s on arm64 and VIP is working but cannot get cloud provider to deploy.

Thanks!

**Comment by braucktoon** [comment]
Never mind, I used the wrong tag, it's v0.0.1

**Comment by thebsdbox** [comment]
The latest release now supports four different architectures!

https://github.com/kube-vip/kube-vip-cloud-provider/pkgs/container/kube-vip-cloud-provider
