### ISSUE TITLE
Manifest doesn't point to the latest release

### ISSUE THREAD

**Issue by evilhamsterman** [kube-vip/kube-vip-cloud-provider#31]
On your website you say you can install the latest release with the manifest located at https://raw.githubusercontent.com/kube-vip/kube-vip-cloud-provider/main/manifest/kube-vip-cloud-controller.yaml.

However that still points to the 0.0.1 release rather than the 0.0.2 release.

**Comment by thebsdbox** [comment]
Fix in #33
