### ISSUE TITLE
Failed to obtain the LoadBalancer IP address

### ISSUE THREAD

**Issue by jieshiyeskey** [kube-vip/kube-vip-cloud-provider#39]
1.env:

 v1.24.3+k3s1
 kube-vip：v0.4.4
 kube-vip-cloud-provider:  v0.0.2
 arp

2.problem：
After kubectl expose deploy nginx --port=80 --type=LoadBalancer is executed, external-IP is always in the Pending state.

3.log:
[root@ah-ap-01 ~]# kubectl logs kube-vip-cloud-provider-0 -n kube-system
I0719 09:47:29.406828       1 serving.go:331] Generated self-signed cert in-memory
W0719 09:47:30.554329       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0719 09:47:30.559632       1 controllermanager.go:127] Version: v0.0.0-master+$Format:%h$
W0719 09:47:30.561301       1 controllermanager.go:139] detected a cluster without a ClusterID.  A ClusterID will be required in the future.  Please tag your cluster to avoid any future issues
I0719 09:47:30.564234       1 secure_serving.go:197] Serving securely on [::]:10258
I0719 09:47:30.564309       1 leaderelection.go:243] attempting to acquire leader lease  kube-system/kube-vip-cloud-controller...
I0719 09:47:30.565157       1 tlsconfig.go:240] Starting DynamicServingCertificateController
I0719 09:47:30.611134       1 leaderelection.go:253] successfully acquired lease kube-system/kube-vip-cloud-controller
I0719 09:47:30.611288       1 event.go:291] "Event occurred" object="kube-system/kube-vip-cloud-controller" kind="Endpoints" apiVersion="v1" type="Normal" reason="LeaderElection" message="kube-vip-cloud-provider-0_ec957898-20c7-44de-940a-d97c31304f4a became leader"
I0719 09:47:30.611633       1 event.go:291] "Event occurred" object="kube-system/kube-vip-cloud-controller" kind="Lease" apiVersion="coordination.k8s.io/v1" type="Normal" reason="LeaderElection" message="kube-vip-cloud-provider-0_ec957898-20c7-44de-940a-d97c31304f4a became leader"
I0719 09:47:30.614564       1 node_controller.go:108] Sending events to api server.
W0719 09:47:30.614660       1 core.go:57] failed to start cloud node controller: cloud provider does not support instances
W0719 09:47:30.614685       1 controllermanager.go:251] Skipping "cloud-node"
I0719 09:47:30.617399       1 node_lifecycle_controller.go:77] Sending events to api server
W0719 09:47:30.617470       1 core.go:76] failed to start cloud node lifecycle controller: cloud provider does not support instances
W0719 09:47:30.617487       1 controllermanager.go:251] Skipping "cloud-node-lifecycle"
I0719 09:47:30.620560       1 controllermanager.go:254] Started "service"
I0719 09:47:30.620606       1 core.go:108] Will not configure cloud provider routes for allocate-node-cidrs: false, configure-cloud-routes: true.
W0719 09:47:30.620714       1 controllermanager.go:251] Skipping "route"
I0719 09:47:30.620737       1 controller.go:239] Starting service controller
I0719 09:47:30.620771       1 shared_informer.go:240] Waiting for caches to sync for service
I0719 09:47:30.724097       1 shared_informer.go:247] Caches are synced for service
I0719 09:50:09.504447       1 event.go:291] "Event occurred" object="default/nginx" kind="Service" apiVersion="v1" type="Normal" reason="EnsuringLoadBalancer" message="Ensuring load balancer"
I0719 09:50:09.553169       1 loadBalancer.go:78] syncing service 'nginx' (d05f7293-bd30-4315-948f-fe4a1794c6c4)
I0719 09:50:09.554412       1 event.go:291] "Event occurred" object="default/nginx" kind="Service" apiVersion="v1" type="Warning" reason="UnAvailableLoadBalancer" message="There are no available nodes for LoadBalancer"
I0719 09:50:09.626388       1 loadBalancer.go:153] no cidr config for namespace [default] exists in key [cidr-default] configmap [kubevip]
I0719 09:50:09.626423       1 loadBalancer.go:156] no global cidr config exists [cidr-global]
I0719 09:50:09.626437       1 loadBalancer.go:175] no range config for namespace [default] exists in key [range-default] configmap [kubevip]
I0719 09:50:09.626446       1 loadBalancer.go:180] Taking address from [range-global] pool
I0719 09:50:09.626557       1 addressbuilder.go:95] Rebuilding addresse cache, [6] addresses exist
I0719 09:50:09.639181       1 loadBalancer.go:121] Updating service [nginx], with load balancer IPAM address [192.168.60.25]
I0719 09:50:09.669527       1 event.go:291] "Event occurred" object="default/nginx" kind="Service" apiVersion="v1" type="Normal" reason="LoadbalancerIP" message=" -> 192.168.60.25"
I0719 09:50:09.669853       1 loadBalancer.go:78] syncing service 'nginx' (d05f7293-bd30-4315-948f-fe4a1794c6c4)
I0719 09:50:09.669884       1 event.go:291] "Event occurred" object="default/nginx" kind="Service" apiVersion="v1" type="Normal" reason="EnsuredLoadBalancer" message="Ensured load balancer"
I0719 09:50:09.669899       1 event.go:291] "Event occurred" object="default/nginx" kind="Service" apiVersion="v1" type="Normal" reason="EnsuredLoadBalancer" message="Ensured load balancer"
I0719 09:50:09.669912       1 event.go:291] "Event occurred" object="default/nginx" kind="Service" apiVersion="v1" type="Normal" reason="EnsuringLoadBalancer" message="Ensuring load balancer"
I0719 09:50:09.669924       1 event.go:291] "Event occurred" object="default/nginx" kind="Service" apiVersion="v1" type="Warning" reason="UnAvailableLoadBalancer" message="There are no available nodes for LoadBalancer"

**Comment by lubronzhan** [comment]
Are you using a single node cluster? Or your pods are on control plane?
Saw this issue here
https://github.com/kubernetes/kubernetes/commit/82d600bb5c34b2c7352643d4d811941e063a8215#diff-56c9c66bf151b9d7268939da6ebf3613R609
The cloud-provider will exclude control plane node from the LB backend pool by default

**Comment by lubronzhan** [comment]
https://github.com/linode/linode-cloud-controller-manager/issues/107#issuecomment-1077665721
Ok according to here, it should be removed since k8s 1.21.
But the kvcp 0.0.3 still use cloud-provider 0.19, I guess that's the root cause.
I checked the code here it excludes control plane nodes https://github.com/kubernetes/cloud-provider/blob/v0.19.4/controllers/service/controller.go#L638-L644
So I guess @thebsdbox it's better to cut a new kube-vip-cp release with new cloud-provider

**Comment by ppathard** [comment]
I am working on on-prem solution. (RKE2, kubevip) Since RKE2 allows scheduling of workloads on control plane nodes and we are not planning to have additional worker nodes ( 3 masters), kubevip for service of type LoadBalancer is not working. 
When this issue would be fixed ?  @lubronzhan

**Comment by lubronzhan** [comment]
That's good news!
Sorry I don't have the permission to cut a release 
@thebsdbox would be the best person to answer when will be another release

**Comment by thebsdbox** [comment]
I'll create a new release tomorrow, but we should look at giving @lubronzhan to maintainer. 😊

**Comment by lubronzhan** [comment]
@ppathard  It should be working with 0.0.4 release.

**Comment by ppathard** [comment]
> 

Thank you @lubronzhan

**Comment by thebsdbox** [comment]
This should now be closed.
