### ISSUE TITLE
kube-vip.io docs point to old manifest?

### ISSUE THREAD

**Issue by sammcgeown** [kube-vip/kube-vip-cloud-provider#5]
Documentation at https://kube-vip.io/hybrid/services/#using-the-plunder-cloud-provider-ccm points to using `https://kube-vip.io/manifests/controller.yaml` to deploy the Plunder Cloud Provider.

That manifest points to `image: plndr/plndr-cloud-provider:0.1.5` which only has an amd64 image. I was able to deploy on arm using `plndr/plndr-cloud-provider:9eb45d26`, which is the current nightly build.

However, as the provider has moved to this repository, it looks like I should be using this manifest - https://github.com/kube-vip/kube-vip-cloud-provider/blob/main/manifest/kube-vip-cloud-controller.yaml, which points to `kubevip/kube-vip-cloud-provider:0.1` and uses the new name.

`kubevip/kube-vip-cloud-provider:0.1` doesn't have an arm build either - however the `latest` tag does.

- It looks like the documentation needs updating to point to the latest kube-vip-cloud-provider manifest?
- It also looks like the manifest needs to point to a multi-arch image, or the 0.1 image needs to be built for multi-arch?

Happy to do a PR for both, if my guesses are correct!

**Comment by thebsdbox** [comment]
Yes please !! I need so much help with the documentation 😂

**Comment by thebsdbox** [comment]
This has now been fixed! Thanks again😀
