### ISSUE TITLE
Question: Will there be a new release for supporting the new annotation method?

### ISSUE THREAD

**Issue by BBQigniter** [kube-vip/kube-vip-cloud-provider#55]
Sorry, but as there are no "discussions" enabled I open this issue.

I have seen [kube-vip v0.5.12](https://github.com/kube-vip/kube-vip/releases/tag/v0.5.12) was released and is now supporting the new annotation-parameter for explicitly setting a VIP, but still there is no new kube-vip-cloud-provider release. But there was some code-change already, see https://github.com/kube-vip/kube-vip-cloud-provider/pull/52

Do I have to add then both in a service-config (spec and annotation) in the meantime until cloud-provider got updated?

**Comment by lubronzhan** [comment]
Dan is working on it. It should be out soon

**Comment by lubronzhan** [comment]
Hi I just released 0.0.5 which has the support @BBQigniter
