### ISSUE TITLE
how to allocate ip address  when multiple lb networks in one namespace?

### ISSUE THREAD

**Issue by todaygood** [kube-vip/kube-vip-cloud-provider#67]
I have 2 multiple kube-vip instances for public network  on eth1  and private network eth0 , now I  understand to use kube-vip-cloud-provider to allocate ip address dynamically, but how to allocate lb  ip address  when multiple networks in one namespace?

in kubevip , https://github.com/kube-vip/kube-vip/pull/546, have implemented  this scene , but I can't find the solution in kube-vip-cloud-provider.

**Comment by lubronzhan** [comment]
I was implementing this as part of https://github.com/kube-vip/kube-vip-cloud-provider/issues/61

**Comment by lubronzhan** [comment]
Now it's done
