### ISSUE TITLE
Feature request: To reduce IP usage, optional feature to allow sharing of existing LoadBalancer IPs if different ports.

### ISSUE THREAD

**Issue by megakid** [kube-vip/kube-vip-cloud-provider#68]
Optionally allow intelligent sharing of LoadBalancer addresses using this feature:

https://kube-vip.io/docs/usage/kubernetes-services/#multiple-services-on-the-same-ip

Example:

When this feature is enabled, if two or more LoadBalancer services requesting non-overlapping ports are configured, the cloud provider will allocate one IP which is shared between the services instead of one per service.

Assuming different ports, this can decrease the amount of IPs in use across a cluster.

**Comment by pnxs** [comment]
I think this should be done with this pull-request: https://github.com/kube-vip/kube-vip-cloud-provider/pull/137

**Comment by lubronzhan** [comment]
Yes, good work!
